CREATE DATABASE bank;
use bank;
CREATE TABLE BANKING(
customer_id INT,
customer VARCHAR(50),
mode VARCHAR(50),
city VARCHAR(50),
PRIMARY KEY(customer_id)
);
INSERT INTO BANKING VALUES(101,"oliva","NETBANKING","PORTLAND");
INSERT INTO BANKING VALUES(102,"ethinol","Credit card","mimi");
INSERT INTO BANKING VALUES(103,"odgwdgh","Credit card","dshhj");
INSERT INTO BANKING VALUES(104,"olivadw","NETBANKING","PORqTLAND");
INSERT INTO BANKING VALUES(105,"oldwa","NETBANKING","PORTLerAND");
INSERT INTO BANKING VALUES(106,"olivwqea","NETBANKING","PORdTLAND");
INSERT INTO BANKING VALUES(107,"oliwva","NETBANKING","PORTLANqweD");
INSERT INTO BANKING VALUES(108,"oliwva","Credit Card","PORTLAN1rD");
INSERT INTO BANKING VALUES(109,"olieva","Credit Card","PORTLAeND");
INSERT INTO BANKING VALUES(110,"oliwva","NETBANKING","PORTLANddD");
INSERT INTO BANKING VALUES(111,"oli1wva","Credit Card","PORTLANDds");

SELECT mode,count(customer) FROM BANKING GROUP BY mode;